Yaru icons improvmenents
  - Use tarball for icons
  - Remove yaru svg icons
  - Fix indentation for consistency

diff --git a/snapcraft.yaml b/snapcraft.yaml
--- a/snapcraft.yaml
+++ b/snapcraft.yaml
@@ -399,18 +399,20 @@ parts:
             glib-compile-schemas usr/share/glib-2.0/schemas
 
     yaru-icons:
-      plugin: nil
-      source: https://github.com/ubuntu/libreoffice-style-yaru-fullcolor.git
-      override-build: |
-        set -eux
-        ./generate-oxt.sh
-        if [ ! -f images_yaru.zip ]; then
-          echo "Yaru icons are missing!";
-          exit 1;
-        fi
-        mkdir -p  $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/config/
-        cp $SNAPCRAFT_PART_BUILD/oxt/iconsets/images_yaru.zip $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/config/
-        cp $SNAPCRAFT_PART_BUILD/oxt/iconsets/images_yaru_svg.zip $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/config/
+        plugin: nil
+        source: https://github.com/ubuntu/libreoffice-style-yaru-fullcolor/archive/refs/tags/2021-03-14.tar.gz
+        override-build: |
+            set -eux
+            cd $SNAPCRAFT_PART_BUILD
+            ./generate-oxt.sh
+            if [ ! -f images_yaru.zip ]; then
+              echo "Yaru icons are missing!";
+              exit 1;
+            fi
+            mkdir -p  $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/config/
+            cp $SNAPCRAFT_PART_BUILD/oxt/iconsets/images_yaru.zip $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/config/
+        build-packages:
+            - unzip
 
     cleanup:
         after: [ desktop-settings-build ]
