Add yaru-icons

diff --git a/snapcraft.yaml b/snapcraft.yaml
--- a/snapcraft.yaml
+++ b/snapcraft.yaml
@@ -37,6 +37,7 @@ parts:
             - gstreamer
             - gtk3-locales
             - desktop-settings-packages
+            - yaru-icons
         plugin: autotools
         source: http://download.documentfoundation.org/libreoffice/src/7.0.3/libreoffice-7.0.3.1.tar.xz
         configflags:
@@ -397,6 +398,20 @@ parts:
             set -eux
             glib-compile-schemas usr/share/glib-2.0/schemas
 
+    yaru-icons:
+      plugin: nil
+      source: https://github.com/ubuntu/libreoffice-style-yaru-fullcolor.git
+      override-build: |
+        set -eux
+        ./generate-oxt.sh
+        if [ ! -f images_yaru.zip ]; then
+          echo "Yaru icons are missing!";
+          exit 1;
+        fi
+        mkdir -p  $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/config/
+        cp $SNAPCRAFT_PART_BUILD/oxt/iconsets/images_yaru.zip $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/config/
+        cp $SNAPCRAFT_PART_BUILD/oxt/iconsets/images_yaru_svg.zip $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/config/
+
     cleanup:
         after: [ desktop-settings-build ]
         plugin: nil
@@ -481,4 +496,4 @@ apps:
         environment: *environment
         plugs:
             - desktop
-            - network
+             network
